### ISSUE TITLE
Accessing data through DbGAP

### ISSUE THREAD

**Issue by Jonbroad15** [billytcl/nanopore_cfDNA#1]
Hi can you please elaborate on how to access the data through DbGAP. I cannot seem to find the files attached to the accession code phs002950 on the website.

**Comment by billytcl** [comment]
Thanks for getting in touch. The study will be released on dbGAP when it makes it out of peer review. Please note that as because the study consists of genomic sequence derived from consented patients, there is an approval and data access request process administered by dbGAP itself (eg. we have no control over this). Google should be able to provide you with more information.
